name: Arxiv Bot

on:
  schedule:
    - cron: "50 0 * * 0,3,4,5,6" # 毎日0時(UTC)に実行
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python paper_arxiv.py
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
